name: Docker Make

on: [push, pull_request]

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
        lang: [cpp, python, dotnet, java]
    env:
      DISTRO: ${{ matrix.distro }}
      LANG: ${{ matrix.lang }}
    steps:
    - uses: actions/checkout@v2
    - name: Build base image
      run: make --directory=ci ${DISTRO}_base
    - name: Build env images
      run: make --directory=ci ${DISTRO}_${LANG}_env
    - name: Build devel images
      run: make --directory=ci ${DISTRO}_${LANG}_devel
    - name: Build project
      run: make --directory=ci ${DISTRO}_${LANG}_build
    - name: Test project
      run: make --directory=ci ${DISTRO}_${LANG}_test
    - name: Package project
      run: make --directory=ci ${DISTRO}_${LANG}_package
