name: Docker Bazel

on: [push, pull_request]

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
        lang: [cpp, python, dotnet, java]
    env:
      DISTRO: ${{ matrix.distro }}
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=bazel ${DISTRO}_env
    - name: Build devel project
      run: make --directory=bazel ${DISTRO}_devel
    - name: Build project
      run: make --directory=bazel ${DISTRO}_build
    - name: Test C++
      run: make --directory=bazel ${DISTRO}_test
